### ISSUE TITLE
Errors when running nixos-rebuild switch

### ISSUE THREAD

**Issue by IonicEcko** [headcounter/shabitica#5]
Hello,

I'm super sorry if it turns out to be noob-ness. I'm trying to run up a shabitica instance and am having all kinds of issues. Important note is that I've never used NixOS before last night so have been limping along based on hours of Google searches and blind luck.

NixOS Version: 18.09
Host: Hyper-V on Server 2019 - Gen-2 UEFI

Installed NixOS based on the instructions [here](https://nixos.org/nixos/manual/index.html#sec-installation-partitioning-UEFI)

Added the hydra channels by running the 2 commands in the readme.
Originally it was failing to get something (sorry didn't take note of it, it was failing to get something from the hydra server). But after finding and running the nix-env -u '*' command in the hydra repo, it doesn't show the error anymore (don't know if it's related).

Using the configuration.nix file [here](https://pastebin.com/jw3u13hu)

Took me forever to get the configuration file not to instantly fail. Had no idea if the code from the readme should be the total config or if it needed to be merged with the default. This config was the closest I've gotten.

Now when I run it, it runs for a while and then hits a ton of errors:
```
fixed-output derivation produced path '/nix/store/zl42hmz2y3xk29iryp96z2zvwya0ykx4-google-fonts-apidoc' with sha256 hash '02y4i0f8xdv5bqzlymir2dqihlf578474453sdrhrw4sijyljp3v' instead of the expected hash '1x0z8r8nb5pj073dyx66b25w9hxs33k07bhbj5cbgf5pyx3589x1'

building '/nix/store/cakyj1q3rnss28mqz0zan47a0jirf0m8-habitica-source-4.92.3.drv'...

cannot build derivation '/nix/store/m90vfamzav4013zhkbi8i7ia71kj1hx0-node-apidoc-0.17.7.drv': 1 dependencies couldn't be built

building '/nix/store/3rxc3wlyq8cyl6vw81yy0j1pqpilqmxb-query-db-version.drv'...

cannot build derivation '/nix/store/4vrjs69kj4z4qfj161zvf2a7g29vz6ny-shabitica-apidoc-4.92.3.drv': 1 dependencies couldn't be built

cannot build derivation '/nix/store/anw1v8h9cj9l90viirfasqlhhqn2lqbf-shabitica-client-4.92.3.drv': 1 dependencies couldn't be built

cannot build derivation '/nix/store/ki19p4aym1rsq20hf7sgywkwbyciy4q3-shabitica-migrator-4.92.3.drv': 1 dependencies couldn't be built

cannot build derivation '/nix/store/58gz8zfaqnysgmrmip6bwhb4rz3i4pfn-shabitica-server-4.92.3.drv': 1 dependencies couldn't be built

cannot build derivation '/nix/store/kjjs3pd2875c4jz54wkq6ziif8zk4byc-closure-info.drv': 1 dependencies couldn't be built

cannot build derivation '/nix/store/94j9jlskbbyjr5981388kl2r1v1kj5jw-nginx.conf.drv': 1 dependencies couldn't be built

cannot build derivation '/nix/store/kmcba83zd91xhpfg2gh2qq5s374wvpc6-unit-script-shabitica-db-update-start.drv': 1 dependencies couldn't be built

cannot build derivation '/nix/store/d7ywbj0qf5q5k71n10h9jnzf2pdf6lff-unit-shabitica.service.drv': 1 dependencies couldn't be built

building '/nix/store/dqsly1xgmvsnpm70h2f2d8k5js9gsj3n-remove-references-to.drv'...

cannot build derivation '/nix/store/w65hmalhwwx1ifwakk017w68yqri9iq5-shabitica-sandbox-paths.drv': 1 dependencies couldn't be built

cannot build derivation '/nix/store/4chz21mp8j7crra28qbrmkzagdy78y7y-system-units.drv': 1 dependencies couldn't be built

cannot build derivation '/nix/store/rygfcxkv2bln3irdlabqwmh8yh5idad0-etc.drv': 1 dependencies couldn't be built

cannot build derivation '/nix/store/n2ais7in5xxki403ac545pizcamcdwsr-nixos-system-habitica-01-18.09.2505.46d3867a08a.drv': 1 dependencies couldn't be built

error: build of '/nix/store/n2ais7in5xxki403ac545pizcamcdwsr-nixos-system-habitica-01-18.09.2505.46d3867a08a.drv' failed
```

Would be happy to write out a "for dummies by a dummy" guide to help others if this is something silly simple?

**Comment by IonicEcko** [comment]
Just noticed the line above all the failures relates to the fonts which there's an open pull request by @Kyren for. 

Unfortunately when I try to clone his repo and build from that (to test) I get nothing but errors while its evaluating the config so there's obviously more to do when running from a cloned repo that I don't know so can't test for sure.

**Comment by aszlig** [comment]
@Runear: Okay, I think it's time to fix the Google fonts issue once and for all by fetching all the fonts from the upstream source repository. You're correct, the issue here is basically #3 and #4.

**Comment by IonicEcko** [comment]
@aszlig I don't want to open another issue when I'm basically just asking for help if you get a spare minute so I'll ask here.

All up and running now with the font sorted, thank you for that! However I have no idea how to get the invites working so I can get a couple of mates trying this with me, any chance you have 5 to drop some hints?

**Comment by aszlig** [comment]
@Runear: Ah, it might make sense to document this better in the README, but registration is only allowed for the first account and subsequent accounts need to be invited either via guilds, groups or via the party.

**Comment by IonicEcko** [comment]
@aszlig Sorry, I probably wasn't very clear, I feel bad asking for help from someone who just does it in their spare time :)

I realise you can only add people to a server by invite, but that invite function for me isn't working. At least I don't think it is. I tried to send an invite from within the app and nothing comes through.

**Comment by aszlig** [comment]
@Runear: Ah, no problem, getting to know where new users are stumbling on allows me to make the whole setup experience a lot easier, so thanks :-)

So, if you didn't you also need configure an MTA, for example via `services.postfix.enable = true`. If you don't want incoming mail, it's probably also a good idea to add `inet_interfaces = 127.0.0.1` to `services.postfix.extraConfig`.

Maybe it's a good idea to add a way to invite users via link rather than via email, so an MTA isn't required.
